FROM registry.redhat.io/ubi8:latest

# Set environment variables for --numcons, --port, and --url
ENV NUMCONS=100
ENV PORT="8080"
ENV URL="localhost"

WORKDIR /app

COPY client /app/

CMD ./client --numcons ${NUMCONS} --port ${PORT} --url ${URL}
