apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector-client
  labels:
    app: connector-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connector-client
  template:
    metadata:
      labels:
        app: connector-client
    spec:
      containers:
        - name: connector-client
          image: quay.io/bryonbaker/connector-client:latest
          command:
          - /bin/bash
          - "-c"
          - |
            export URL="connector-server"
            export PORT="8080"
            export NUMCONS="1000"
            export XCHNG="2"
            echo $NUMCONS
            echo $URL
            echo $PORT
            echo $XCHNG
            exec /app/client --numcons $NUMCONS --port $PORT --url $URL --xchng $XCHNG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
