apiVersion: v1
kind: Service
metadata:
  name: connector-server
spec:
  selector:
    app: connector-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector-server
  labels:
    app: connector-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connector-server
  template:
    metadata:
      labels:
        app: connector-server
    spec:
      containers:
        - name: connector-server
          image: quay.io/bryonbaker/connector-server:latest
          command:
          - /bin/bash
          - "-c"
          - |
            export PORT="8080"
            export XCHNG="2"
            echo $PORT
            echo $XCHNG
            exec /app/client --port $PORT --xchng $XCHNG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080